<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Brand.aspx.cs" Inherits="StayBeautifulSMS.Brand" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <div>
        <div>
            <asp:Label ID="Label4" class="headings" runat="server" Text="Brand"></asp:Label>
        </div>
        <br />
        <br />
        <div>
            <asp:Label runat="server" class="labels" ID="Label1" Font-Bold="True" Text="Brand Name"></asp:Label>
            <br />
            <asp:TextBox ID="txtBrandName" Height="25px" runat="server" Width="300px"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="txtBrandName" ErrorMessage="Takes string value only!" ForeColor="Red" ValidationGroup="CustomerGroup" ValidationExpression="^[a-zA-Z ]+$"></asp:RegularExpressionValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtBrandName" ErrorMessage="Field must not be empty!" ForeColor="Red" ValidationGroup="CustomerGroup"></asp:RequiredFieldValidator>
        </div>
        <br />
        <br />
        <br />
         <div>
             <asp:GridView ID="brandGridView" DataKeyNames="BRAND_ID" Height="369px" HorizontalAlign="Justify" Width="1136px" CellPadding="5" CellSpacing="5" GridLines="Horizontal" runat="server" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" PageSize="15" ><%--OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" --%>

             </asp:GridView>
        </div>
    </div>
</asp:Content>