<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="Item.aspx.cs" Inherits="StayBeautifulSMS.Item" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
      <div>
        <div>
            <asp:Label ID="Label4" class="headings" runat="server" Text="Items"></asp:Label>
        </div>
        <br />
        <br />
        <div>
            <asp:Label runat="server" class="labels" ID="Label1" Font-Bold="True" Text="Item Name"></asp:Label>
            <br />
            <asp:TextBox ID="txtItemName" Height="25px" runat="server" Width="300px"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="txtItemName" ErrorMessage="Takes string value only!" ForeColor="Red" ValidationGroup="CustomerGroup" ValidationExpression="^[a-zA-Z ]+$"></asp:RegularExpressionValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtItemName" ErrorMessage="Field must not be empty!" ForeColor="Red" ValidationGroup="CustomerGroup"></asp:RequiredFieldValidator>
        </div>
        <br />
                <div>
            <asp:Label runat="server" class="labels" ID="Label2" Font-Bold="True" Text="Item Description"></asp:Label>
            <br />
            <asp:TextBox ID="txtItemDescription" Height="25px" runat="server" Width="300px"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ControlToValidate="txtItemDescription" ErrorMessage="Takes string value only!" ForeColor="Red" ValidationGroup="CustomerGroup" ValidationExpression="^[a-zA-Z ]+$"></asp:RegularExpressionValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="txtItemDescription" ErrorMessage="Field must not be empty!" ForeColor="Red" ValidationGroup="CustomerGroup"></asp:RequiredFieldValidator>
        </div>
        <br />
                <div>
            <asp:Label runat="server" class="labels" ID="Label3" Font-Bold="True" Text="Stock Date"></asp:Label>
            <br />
            <asp:TextBox ID="txtStockDate" Height="25px" runat="server" Width="300px"></asp:TextBox>
        </div>
        <br />
                <div>
            <asp:Label runat="server" class="labels" ID="Label5" Font-Bold="True" Text="Available Quantity"></asp:Label>
            <br />
            <asp:TextBox ID="txtAvailableQuantity" Height="25px" runat="server" Width="300px"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator4" runat="server" ControlToValidate="txtAvailableQuantity" ErrorMessage="Takes string value only!" ForeColor="Red" ValidationGroup="CustomerGroup" ValidationExpression="^[0-9]+$"></asp:RegularExpressionValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="txtAvailableQuantity" ErrorMessage="Field must not be empty!" ForeColor="Red" ValidationGroup="CustomerGroup"></asp:RequiredFieldValidator>
        </div>
        <br />
                <div>
            <asp:Label runat="server" class="labels" ID="Label6" Font-Bold="True" Text="Item Rate"></asp:Label>
            <br />
            <asp:TextBox ID="txtItemRate" Height="25px" runat="server" Width="300px"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator5" runat="server" ControlToValidate="txtItemRate" ErrorMessage="Takes string value only!" ForeColor="Red" ValidationGroup="CustomerGroup" ValidationExpression="^[0-9]+$"></asp:RegularExpressionValidator>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="txtItemRate" ErrorMessage="Field must not be empty!" ForeColor="Red" ValidationGroup="CustomerGroup"></asp:RequiredFieldValidator>
        </div>
        <br />
        <br />
        <br />
         <div>
             <asp:GridView ID="itemGridView" DataKeyNames="ITEM_ID" Height="369px" HorizontalAlign="Justify" Width="1236px" CellPadding="5" CellSpacing="10" GridLines="Horizontal" runat="server" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" PageSize="15" ><%--OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" --%>

             </asp:GridView>
        </div>
    </div>
</asp:Content>